### ISSUE TITLE
Read Avro Data using DatumReader

### ISSUE THREAD

**Issue by gautampunhani** [Achal-Aggarwal/workerbee#14]
Not able to read Avro Data which was inserted with following parameters in a hql:

set hive.exec.compress.output=true;
set avro.output.codec=deflate;
set avro.mapred.deflate.level=9;

**Comment by Achal-Aggarwal** [comment]
Thanks @gautampunhani for reporting the issue.

To read/unload data, workerbee first writes data to some temporary directory. The purpose is to make the final output format text as INSERT OVERWRITE DIRECTORY always write in TEXT format. Another goal is to denormalise/flatten the partitions. 

So even if avro data is compressed with X codes and N deflate level, hive reads it and emits plain text on doing INSERT OVERWRITE DIRECTORY.

The problem here is **hive.exec.compress.output**. When sets to true, hive always compresses the map/reduce output. So even if insert directory is called on a text table output would be unreadable.

The solution is to set hive.exec.compress.output=false before taking a dump of data into a directory to read as plain text.

Fixed in commit 095b6f6e46c

If you are using version less than 3.1-SNAPSHOT, please execute "set hive.exec.compress.output=true" before running any unload statements.
